[package]
name = "pico_measure_transport"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.7.17"
postcard = "1.1.1"
serde = { version = "1.0.*", default-features = false }

[dev-dependencies]
libc-print = "0.1.23"